[package]
name = "moose-service"
version.workspace = true
edition = "2024"

[[bin]]
name = "moose-service"
path = "src/main.rs"

[dependencies]
moose-rack = { path = ".." }
anyhow = "1.0.104"
axum = { version = "0.8", features = ["multipart"] }
clap = { version = "4.6.5", features = ["derive", "env"] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.4"
md-5 = "0.11.0"
hex = "0.4.3"
sha1 = "0.11.0"
rusqlite = { version = "0.37", features = ["bundled"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net"] }
tower-http = { version = "0.6", features = ["fs", "trace"] }
tower = { version = "0.5", features = ["util"] }

[dev-dependencies]
tempdir = "0.3"
